### ISSUE TITLE
message-of-the-day-configuration.update-type has no effect

### ISSUE THREAD

**Issue by kitt-schlatter** [kerpsonn/CrazyMotd#23]
When configuring the message of the day, the `update-type` field appears to have no effect on the behavior of message rotation. Regardless of whether it's set to `RANDOM` or `QUEUE` it will first select the third listed motd (or the first if there are less than three) and go through them sequentially from there. Additionally, it will reset this looping behavior, starting with the third (or first) option again on every server restart. This means that any server which restarts regularly will go through the same list of options in the same order after every restart even when `RANDOM` is selected.

**Comment by kerpsonn** [comment]
Actually something is up, thank you for the notification!

**Comment by kerpsonn** [comment]
Fix: #32
